export const BOX_ARBITRUM_ADDRESS = process.env.NEXT_PUBLIC_BOX_ARBITRUM_ADDRESS;

export const POLYGON_CHAIN_ID = process.env.NEXT_PUBLIC_POLYGON_CHAIN_ID;

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

export const ALCHEMY_API_KEY = process.env.NEXT_PUBLIC_ALCHEMY_API_KEY;

export const TOKENIZE_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_TOKENIZE_CONTRACT_ADDRESS;

export const REWARD_READER_ADDRESS = process.env.NEXT_PUBLIC_REWARD_READER_ADDRESS;

export const FEE_TOKEN_ADDRESS = process.env.NEXT_PUBLIC_FEE_TOKEN_ADDRESS;

export const MARKET_URL = process.env.NEXT_PUBLIC_MARKET_URL;
